### ISSUE TITLE
Repeater Fields shows HTML tags on pages: *Foo* shown as "<em>Foo</em>" (when using Markdown)

### ISSUE THREAD

**Issue by klor** [processwire/processwire-issues#1481]
### Short description of the issue

When showing page contents from a Repeater field on "Page Edit" (in the administration), contents are shown with HTML tags (when the field uses Markdown).

### Expected behavior

Repeater field contents that uses Markdown ("*Foo*") are shown as text in "Page Edit".

This is similar to how Repeater field contents are shown in the Page Tree - here, HTML tags are stripped from {mymarkdownfield} when this field is shown in the Page Tree.

### Actual behavior

When viewing the page in Page Tree, *Foo* is shown as "<em>Foo</em>" (when using Markdown)

### Optional: Suggestion for a possible fix

Repeater Fields shall strip_tags before shown on "Page Edit".

### Steps to reproduce the issue

1. On Page template, add a Repeater with field Title.
2. Title field uses the "HTML Entity Encoder" Text Formatter by default.
3. Template: Set "List of fields to display in the admin Page List" to {title} (default).
3. Create the page "*Foo*".
4. View the page in Page Tree, you now see "<em>Foo</em>" (the HTML tags are visible).

* ProcessWire version:

ProcessWire 3.0.184

**Comment by ryancramerdesign** [comment]
@klor I'm not sure I fully understand yet. Repeaters don't contribute anything to the page list (or change the behavior of it) so I'm wondering if/how repeaters relate here, and can you observe the issue without repeaters? Also, the HTML Entity Encoder does appear to be applying if you are seeing literal `<em>` HTML tags in your page titles, so I think what you might be looking for is it to strip_tags *before* it applies the entity encoder? (or do I have that wrong?)

**Comment by klor** [comment]
@ryancramerdesign 
You're right - it's not the page list.

I have: 
* Fields added to my template are:
	* Field 'books' (repeater). 'Details' -> 'Repeater item labels': {book_title}.
	* Field 'book' (text). Text formatter 'Markdown/Parsedown Extra'.
* Page book title is 'This is *one* **great** book'.

Scenario 1: Show repeater field contents in Page Edit (fails: {book_title} shows HTML tags).
![books-pageedit-repeater](https://user-images.githubusercontent.com/129573/145665109-1d54afc8-3f74-4fb8-9c43-44ea7726e80c.png)

Screenshot: Repeater books:
![repeater books](https://user-images.githubusercontent.com/129573/145665315-9c256cbc-4c27-47f9-8885-09b19062300a.png)

Screenshot: Repeater books book_title:
![repeater books book_title](https://user-images.githubusercontent.com/129573/145665318-8259ccdc-741a-4758-aae1-6e8264e8d95a.png)


Scenario 2: Show repeater field contents in Page Tree (works: {book_title} shown as expected)
{title} - {books.first.book_title}

![books-pagetree](https://user-images.githubusercontent.com/129573/145665111-cbeee9c9-c784-4716-8aec-f2b134b511b2.png)

**Comment by ryancramerdesign** [comment]
@klor Thanks, those screenshots were helpful. I've pushed an update that should make it do text-only in the repeater label. Though I'm a little worried it might lead to more opened issues, as it seems like we've been back and forth on whether the label should show the encoded markup or not. But so far it seems to me like what you are suggesting is the best route. Note that since you are using Markdown/Parsedown I'd suggest installing the core TextformatterPStripper module and letting that apply after Markdown... that will just remove the unnecessary paragraph tags around single-line markdown.

**Comment by adrianbj** [comment]
@ryancramerdesign - I feel like this is related. I am seeing remnants of entities, eg:
![image](https://user-images.githubusercontent.com/871211/148668450-0efd969b-fb83-42f4-8752-847a8355e6e9.png)

This is from 3.0.190, but I just tries 3.0.192 and it's still an issue. Can you reproduce this?

**Comment by ryancramerdesign** [comment]
@adrianbj I can't duplicate that one here, but it's been a few versions since you posted this. Let me know if still seeing it.

**Comment by adrianbj** [comment]
@ryancramerdesign - this was fixed a few versions ago - thank you.

**Comment by ryancramerdesign** [comment]
@adrianbj Okay great, thanks. I'll close.
