### ISSUE TITLE
Can't use cyrillic characters in WireMail from name and attachments name

### ISSUE THREAD

**Issue by esl51** [processwire/processwire-issues#1681]
### Short description of the issue

I can't use cyrillic characters in WireMail from name and attachments name.

### Expected behavior

E-mail is received.

### Actual behavior

E-mail is not received.

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

Your possible fix goes here.

### Steps to reproduce the issue

This code is working as expected (e-mail received with attachment).

```php
$m = $mail->new();
$m->to('your@email.com');
$m->from('noreply@' . wire('config')->httpHost);
$m->fromName('Galaxy partners');
$m->subject('Partners test');
$m->bodyHTML('<p>Test</p>');
$m->attachment(wire('config')->paths->root . 'tmp/test.pdf', 'Attachment.pdf');
return $m->send();
```

This code is not working as expected (e-mail did not received at all).

```php
$m = $mail->new();
$m->to('your@email.com');
$m->from('noreply@' . wire('config')->httpHost);
$m->fromName('Партнёры по галактике');
$m->subject('Tecт от партнёров');
$m->bodyHTML('<p>Тест</p>');
$m->attachment(wire('config')->paths->root . 'tmp/test.pdf', 'Вложение.pdf');
return $m->send();
```

### Setup/Environment

* ProcessWire version:
* (Optional) PHP version: 7.4.32
* (Optional) MySQL version: Ver 15.1 Distrib 10.1.48-MariaDB
* (Optional) Any 3rd party modules that are installed and could be related to the issue:

**Comment by ryancramerdesign** [comment]
@esl51 Testing here, I can duplicate the issue with the "from" name. Though no issues with cyrillic anywhere else, including the subject, attachment, body, which seems to work okay in testing here. This is testing with just plain WireMail. If I test with a WireMail module (WireMailMailgun in my case) then the fromName also works. I'm unsure if that's the result of some code in WireMailMailgun or something at the Mailgun service.

I'm not positive if the issue is in WireMail or the SMTP server, but am going to assume WireMail for now, since we are both seeing it. It would seem that the fromName needs some kind of different encoding beyond just quoted printable. I tried duplicating the encoding used for the subject, but that didn't help. I don't know for sure what the solution is, so am going to add a help-needed tag to this in case someone else knows.  Thanks.

**Comment by esl51** [comment]
I don't use any modules in this case. Tested the code on another server and there is no problem with attachments. But the problem with long "from" is also confirmed.

**Comment by esl51** [comment]
I installed the [WireMailPHPMailer](https://processwire.com/modules/altivebirit/) module and everything worked. Perhaps you should see how this point is implemented in PHPMailer.

**Comment by BitPoet** [comment]
Editing my earlier comment: there's just an issue of line wrapping at the correct spot. Shouldn't be that hard to fix. I'll give it a try.

**Comment by BitPoet** [comment]
There's an updated WireMail.php [here in my processwire-wiremail fork](https://github.com/BitPoet/processwire-wiremail/tree/dev). I want to test it a little more before I feel comfortable creating a pull request, but the first tests look promising. If anybody wants to give it a spin, feel free.

I rewrote a little more than initially thought. Encoding and wrapping should now work correctly for from:, to: and reply-to:.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign, still present, but only half the bug remains in 3.0.271.

What's already fixed: fromName() and subject() both go through WireMail::encodeMimeHeader() (mb_encode_mimeheader, RFC 2047), so Cyrillic From-names and subjects are properly encoded already. What's still broken: WireMail::renderMailAttachments() (wire/core/WireMail/WireMail.php) embeds the attachment filename raw, unencoded into the MIME headers.

**Suggested fix:**
```diff
diff --git a/wire/core/WireMail/WireMail.php b/wire/core/WireMail/WireMail.php
index bf39b12..85d6f13 100644
--- a/wire/core/WireMail/WireMail.php
+++ b/wire/core/WireMail/WireMail.php
@@ -776,11 +776,14 @@ class WireMail extends WireData implements WireMailInterface {
 	
 			if(stripos($content, $boundary) !== false) continue;
 			
+			// encode non-ASCII filenames (rfc2047), same as is already done for Subject/From
+			$filenameHeader = $this->encodeMimeHeader($filename);
+			
 			$body .=
 				"--$boundary\r\n" .
-				"Content-Type: application/octet-stream; name=\"$filename\"\r\n" .
+				"Content-Type: application/octet-stream; name=\"$filenameHeader\"\r\n" .
 				"Content-Transfer-Encoding: base64\r\n" .
-				"Content-Disposition: attachment; filename=\"$filename\"\r\n\r\n" .
+				"Content-Disposition: attachment; filename=\"$filenameHeader\"\r\n\r\n" .
 				"$content\r\n\r\n";
 		}
```
