### ISSUE TITLE
findMany() issue with outputFormatting, not consistent with find()

### ISSUE THREAD

**Issue by er314** [processwire/processwire-issues#2126]
a page obtained via get() or find() initially has its outputFormatting at true, 
while a page obtained via findMany() does not ; I would expect that it does, too.
 
```php

$id = 9739;  // or whatever

$pg = pages()->get("id={$id}");
echo (int)$pg->of();  // of=1

$arrPg = pages()->find("id={$id}");
$pg = $arrPg->first();
echo (int)$pg->of();  // of=1

$arrPgMany = pages()->findMany("id={$id}");
$pg = $arrPgMany->first();
echo (int)$pg->of();  // of=0 !!!

```

PW 3.0.242 & 3.0.251

**Comment by ryancramerdesign** [comment]
@er314 Since you used findMany() the page is a lazy-loading placeholder. It isn't technically loaded until you access something from it. If you update your example to this, then you should get the correct output formatting state:
~~~~~
$arrPgMany = pages()->findMany("id={$id}");
$pg = $arrPgMany->first();
$pg->title; // triggers page to load
echo (int)$pg->of(); 
~~~~~

**Comment by er314** [comment]
@ryancramerdesign hmm... now look at this : 

```php
$arrPgMany = pages()->findMany("id={$id}");
$pg = $arrPgMany->first();
$pg->getFormatted("title"); // alternate triggers page to load... but not lazy-loading-friendly
$pg->title; // re-triggers page to load, better safe than sorry
echo (int)$pg->of(); // -> but nope, 0 again
```

All in all, this doesn't give confidence in using findMany() interchangeably with find()

**Comment by er314** [comment]
hello @ryancramerdesign ,
please reassess with my updated example above, where $pg->getFormatted() breaks the status of $pg->of()

**Comment by adrianbj** [comment]
Might be worth looking into this at the same time: https://github.com/processwire/processwire-issues/issues/2105

**Comment by matjazpotocnik** [comment]
@er314 this should be fixed in https://github.com/processwire/processwire/commit/258b41cb877b8e77bc0d1a0e4a15e0d287416210

**Comment by er314** [comment]
@matjazpotocnik, @ryancramerdesign,
with https://github.com/processwire/processwire/commit/258b41cb877b8e77bc0d1a0e4a15e0d287416210 applied,
 I confirm that findMany() followed by of() is now fully consistent with find() followed by of() :
- the bug where getFormatted() was breaking the status of of(), is no more
- the undefined of() before any access to a page field, is no more

**Comment by adrianbj** [comment]
I am glad the `getFormatted()` bug is  fixed, but I can see this breaking lots of sites that have unknowingly relied on this bug.

I assume it has also fixed #2105 but I haven't tested yet.

**Comment by adrianbj** [comment]
@ryancramerdesign @matjazpotocnik  - to follow up - I just tested and the fix for this does not fix issue #2105

**Comment by matjazpotocnik** [comment]
@adrianbj I know, already tested...

**Comment by er314** [comment]
> I am glad the `getFormatted()` bug is fixed, but I can see this breaking lots of sites that have unknowingly relied on this bug.
> 

Regarding the bug itself, 
the new behavior is that of() now behaves exactly the same on a page obtained via findMany(), compared to obtained via find(),
therefore I have a hard time envisioning that "lots of sites" would break due to this,
or you are referring to how the bug is fixed, causing other side effects ?

**Comment by adrianbj** [comment]
@er314 - my point is that if a `getFormatted()` call was changing the formatted status of a page and now it isn't, then there might be code out there in production that is relying on that change.

I am still glad it's fixed, but I do wonder if it might break some things, either output or API saving for those sites.
