### ISSUE TITLE
Page name anomolies for page titled "Untitled 1"

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#666]
### Short description of the issue

This is a weird one, and was raised by PCuser in the forums: https://processwire.com/talk/topic/19769-page-url-changes-when-page-is-saved/

This is the page tree (clean PW installation, no modules or hooks):
![2018-08-12_092943](https://user-images.githubusercontent.com/1538852/43996268-0b114e0e-9e13-11e8-8e1c-b03226696e12.png)
Note that there is only a single child page "Untitled 1" under its parent.

When that page is edited, on every save the page name changes - in this case alternating between "untitled-1" and "untitled-1-2". PCuser reported a different change where the suffix number was incrementing upwards after each save.

Also, if I manually set the page name to "untitled-2" I get a message about the name being changed because that name was already taken, but that is incorrect because there are no sibling pages that the name could clash with. This is on PW 3.0.108 so probably related to this issue: https://github.com/processwire/processwire-issues/issues/648

![page-name](https://user-images.githubusercontent.com/1538852/43996302-14f419a0-9e14-11e8-86a1-e4f523772270.gif)

### Setup/Environment

* ProcessWire version: 3.0.108

**Comment by matjazpotocnik** [comment]
In my case, on save, the page name iterates between untitled-1 and untitled-1-13. It goes back to at least PW 3.0.40

**Comment by matjazpotocnik** [comment]
It looks like this is happening in PagesEditor.php in the setupPageName method. I fixed it by replacing `&&` with `||` in `if($pageName == $this->untitledPageName && strpos($page->name, $this->untitledPageName) === 0) {` I'm not sure if this is how it should be fixed...

**Comment by ryancramerdesign** [comment]
I'm not currently seeing this issue, but I think it might be because a lot of the code for this stuff was completely replaced with the addition of the PagesNames class to the core. Are you still seeing the issue there on the most recent core dev branch versions? Thanks.

**Comment by netcarver** [comment]
@ryancramerdesign Bumping this for your further consideration.

**Comment by ryancramerdesign** [comment]
@Toutouwai @netcarver I can't seem to reproduce that one. I'm able to create a page with name untitled-2 no problem here. Any other conditions present you can think of?

**Comment by Toutouwai** [comment]
> I'm able to create a page with name untitled-2 no problem here.

The issue isn't with creating a page named untitled-2, it's with changing the name of a page titled untitled-1 to untitled-2.

I retested in the latest v3.0.127 and the issue remains.

Only a single page under the parent (no page named untitled-2):
![2019-03-09_142356](https://user-images.githubusercontent.com/1538852/54064225-510f2800-4277-11e9-8693-481147af2a63.png)

Rename fails:
![names](https://user-images.githubusercontent.com/1538852/54064227-52405500-4277-11e9-8642-85fa5b00d681.gif)

**Comment by matjazpotocnik** [comment]
Looking this method at in PageNames.php
```
	/**
	 * Check given page’s name for conflicts and increment as needed while also triggering a warning notice
	 * 
	 * @param Page $page
	 * @since 3.0.127
	 * 
	 */
	public function checkNameConflicts(Page $page) {
        ...
            $page->name = $page->namePrevious;
        ...
        }
```

Shouldn't that $page parameter be passed by reference?

But the cause of this "untitled" issue is in PagesEditor.php in savePageQuery():

```
		if($this->pages->names()->isUntitledPageName($page->name)) {
			$this->pages->setupPageName($page);
		}
```
That eventually call pageNameFromFormat() method and that set the page name from your title "Untitled 1". Perhaps we shouldn't use the word "untitled" as the title or name? Or maybe this:

```
		if($isNew && $this->pages->names()->isUntitledPageName($page->name)) {
			$this->pages->setupPageName($page);
		}

```

**Comment by ryancramerdesign** [comment]
> Shouldn't that $page parameter be passed by reference?

Objects are always passed by reference in PHP. You would have to make a clone of the object in order for it not to be. 

> Perhaps we shouldn't use the word "untitled" as the title or name?

The "untitled-" is a used as a reserved word for auto-naming of pages, so if giving it that name then it's going to manage the name and increments. As I understand it @Toutouwai needs to literally use the name "untitled-2" for a page? If that's the case, that's definitely going to confuse PW since it thinks it is managing the name when it has the "untitled-" in it. I suppose we could provide an option to configure what the reserved word is for untitled page names. The only drawback there is that if there are any already in the system, it would lose track of the others.

**Comment by ryancramerdesign** [comment]
@matjazpotocnik Good idea, but in this case I don't think adding the $isNew to the if() statement will solve it because the untitled name would be adjusted to the name format once the fields comprising the name format are available, and this usually happens after the page is no longer new.

**Comment by matjazpotocnik** [comment]
@ryancramerdesign 
> Objects are always passed by reference in PHP. You would have to make a clone of the object in order for it not to be.

Ouch, didn't know that. Thanks for the info, we learn every day.

> The "untitled-" is a used as a reserved word for auto-naming of pages, so if giving it that name then it's going to manage the name and increments.

Yes, that's clear.

> I suppose we could provide an option to configure what the reserved word is for untitled page names. The only drawback there is that if there are any already in the system, it would lose track of the others.

I don't think this is a good idea.

What I meant by "we shouldn't use the word untitled" is that this should be somehow/somewhere documented so we are aware that untitled is "reserved word".

> Good idea, but in this case I don't think adding the $isNew to the if() statement will solve it because the untitled name would be adjusted to the name format once the fields comprising the name format are available, and this usually happens after the page is no longer new.

I have tried my "fix" and haven't found any issues with it, but of course I might overlooked something. @Toutouwai (or anyone), could you try?

**Comment by Toutouwai** [comment]
Adding $isNew to the if() statement does solve the issue, but I'm not sure of the purpose of that part that calls setupPageName() so don't know if the change has any unwanted consequences.

I'm also not too clear on the circumstances that cause pages to be created without names that would necessitate the "untitled" prefix. Is this something that happens only temporarily, or very rarely? If so perhaps the reserved word could be some string that is unlikely to be used deliberately as a page name. The word "untitled" followed by a number is something that occurs frequently as the title of artworks, so it wouldn't be that rare to have pages that are deliberately named along these lines.

**Comment by ryancramerdesign** [comment]
The untitled name is used when a page is using a name format based on other fields, and those fields are not yet available/populated. It'll retain that name until the fields are available, which is why the $isNew solution wouldn't be reliable. I understand what you mean about artworks with the name untitled. I just checked and it looks like we already have a $config setting for this:
~~~~
$config->pageNameUntitled = "untitled";
~~~~
If you set that to something else in your /site/config.php I think that'll likely enable you to use the page names that you want, though let me know if not.

**Comment by Toutouwai** [comment]
Thanks, customising that $config setting fixes the issue.
