### ISSUE TITLE
 Error when adding new page with non-ascii characters in a page field 

### ISSUE THREAD

**Issue by gideonso** [processwire/processwire-issues#724]
### Short description of the issue

 Error when adding new page with non-ascii characters in a page field 

### Expected behavior

Page should be successfully created without any error.

### Actual behavior

Error occurs and page not get created

### Optional: Screenshots/Links that demonstrate the issue

![2018-10-13 09-46-10](https://user-images.githubusercontent.com/16899800/46899935-e4148380-cecc-11e8-80a8-f0581d64d275.png)

### Optional: Suggestion for a possible fix

NIL

### Steps to reproduce the issue

1. create a page reference field that allows user to create new page in the page edit page. 
2. try to create a new page with non ASCII characters in the page reference field.
3.  got this error:

Error adding page "一二三" - SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='

### Setup/Environment

* ProcessWire version: this bug was introduce in 3.0.111 and remains till 3.0.115
* (Optional) PHP version: 7.2.10 and 5.6.29

**Comment by gideonso** [comment]
Hi @ryancramerdesign 

I think it is urgent to take a look on this newly introduced issue.

Gideon

**Comment by BitPoet** [comment]
The exception occurs when [executing the query in PageNames::pageNameExists](https://github.com/processwire/processwire/blob/dev/wire/core/PagesNames.php#L562), and the reason is that the pages.name column is explicitly set to ascii character set at creation in [install.sql](https://github.com/processwire/processwire/blob/dev/wire/core/install.sql#L287).

@ryancramerdesign: I don't think there is still a compelling reason for pages.name still having to be ascii (correct me if I'm wrong) since all input through core methods is sanitized anyway if $config->pageNamesCharset is still ascii.

As a workaround, one can change the charset for the name column manually after installation by executing the following MySQL statement:
```mysql
ALTER TABLE pages MODIFY COLUMN `name` varchar(128) character set utf8 NOT NULL;
```
Replace utf8 with utf8mb4 if you selected that character set at installation time.

**Comment by gideonso** [comment]
Thanks for the work around. If it is a multi-language site, there are more than one name column. Do I need to change all of them to utf8 or utf8mb4??

**Comment by BitPoet** [comment]
> If it is a multi-language site, there are more than one name column. Do I need to change all of them to utf8 or utf8mb4?

Yes, LanguageSupportPageNames also adds new name columns with an ascii charset.

**Comment by AndZyk** [comment]
Hello,

this issues doesn't only affect the page field but also creating new pages regular.

I have many multi-language sites which use the nice UTF8-page names feature:
`$config->pageNameCharset = 'UTF8'; `

First introduced [here](https://processwire.com/blog/posts/hello-%E5%81%A5%E5%BA%B7%E9%95%B7%E5%A3%BD%C2%B7%E7%B9%81%E6%A6%AE%E6%98%8C%E7%9B%9B/).

Often I want Umlauts in every language name, but I can only have Umlauts in the default language name. It is not possible anymore to have Umlauts in another language, like it used to. This is a little bit annoying and I hope this will be fixed.

Regards, Andreas

**Comment by gideonso** [comment]
I don't have problem with creating new page with non-ascii character but I do think thios issue really worth Ryan to take a look at it.

**Comment by ryancramerdesign** [comment]
ProcessWire always stores page names as ascii. When using UTF-8 for the charset, it stores them as encoded UTF-8 which is ascii compatible. I don't recommend changing your character set on the name field. I think the issue here is that the highlighted pageNameExists() method in /wire/core/PagesNames.php needs to perform this encoding conversion, and it isn't at present. I've just pushed a possible fix for this. Can you let me know if you find it does/doesn't fix it? Thanks.

**Comment by gideonso** [comment]
Hi @ryancramerdesign,

I reverted the name field to ascii general ci collation and confirmed that your commit fixed this issue. Thanks for your hard work.

**Comment by AndZyk** [comment]
Hello @ryancramerdesign,

I am not sure if this is related, but I also want to confirm that with the newest changes it is possible to add new pages with Umlauts in different languages. But you still get an error notification after saving the page, even though it saved corret.

Add new page:

![designconcepts dc_processwire_page_add__parent_id 1020 template_id 46](https://user-images.githubusercontent.com/9403850/49276905-1af42800-f480-11e8-9f03-0f69fdd24fe7.png)

Error notification after saving:

![designconcepts dc_processwire_page_edit__id 2312 new 1](https://user-images.githubusercontent.com/9403850/49276907-1b8cbe80-f480-11e8-8f54-00af101ef512.png)

Saved page name with Umlauts in different languages correct:

![designconcepts dc_processwire_page_edit__id 2312 new 1 1](https://user-images.githubusercontent.com/9403850/49276906-1b8cbe80-f480-11e8-9527-0cb632884f9b.png)

Thank you for looking into this.

Regards, Andreas

**Comment by gideonso** [comment]
Hi @AndZyk,

Can you confirm if this bug is fixed?? If it is fixed, I will close this issue.

Gideon

**Comment by gideonso** [comment]
Hi @AndZyk @ryancramerdesign ,

The problem @AndZyk mentioned does exist with latest version if multi-language support is enabled.

There is no problem with only 1 language.

Gideon

**Comment by ryancramerdesign** [comment]
In your /site/config.php file can you provide the value you have for `$config->pageNameCharset` and `$config->pageNameWhitelist` (if present) ?

**Comment by gideonso** [comment]
$config->pageNameCharset = "UTF8"
$config->pageNameWhitelist = <<A very long Chinese Character List>>

**Comment by ryancramerdesign** [comment]
Thanks @gideonso and @AndZyk , I was able to duplicate and think I've got this one fixed now. Can you confirm? Thanks.

**Comment by AndZyk** [comment]
@ryancramerdesign For me it is fixed now. I can save a page with Umlauts in different languages and without error notification. Thank you for fixing this.

**Comment by ryancramerdesign** [comment]
@AndZyk Thanks for testing, glad to hear it seems to be working now.

**Comment by gideonso** [comment]
@ryancramerdesign 

One more issue though, for utf8 page name, we need to whitelist characters both in config.php and .htaccess 16A or 16B. But there is a very long list of Chinese Characters. I found that if the number of characters put in the .htaccess file exceeds certain number causes 500 error. Is there any way to whitelist all the utf8 character with a more convenient way?

Gideon

**Comment by netcarver** [comment]
@gideonso As your original issue seems to be fixed, please could you close this issue and open a new github issue to track your new request/report. Many thanks.

**Comment by netcarver** [comment]
/remind me to review and close if necessary in 1 week

**Comment by ghost** [comment]
Unfortunately this error is present again with the latest development version 3.0.127 + the newest commits from this week:

`PDOException SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation`

This happens when I try to add a new page and enter a Umlaut (äöü).

Can somebody please confirm this?

Regards, Andreas

**Comment by netcarver** [comment]
Hi Andreas, thank you for the report - re-opening to track this.

**Comment by ryancramerdesign** [comment]
Thanks @AndZyk I was also able to duplicate that and have pushed a fix.

**Comment by ghost** [comment]
Sorry for opening this topic again, but it seems that with the latest version 3.0.128 + the newest commits from this weeks, you cannot save page names with an Umlaut.

After adding a page, the page name field is blank and you get an error, that the page name is a required field. Also existing page names with a Umlaut are blank after the update without editing.

I hope this is enough information. If not I try to explain it further.

Regards, Andreas

**Comment by ryancramerdesign** [comment]
@AndZyk Can you paste in your `$config->pageNameCharset` and $config->pageNameWhitelist` settings from your /site/config.php file? Thanks.

**Comment by ghost** [comment]
Of course:

`$config->pageNameCharset = 'UTF8';`
`$config->pageNameWhitelist = '';`

I have read, that you can leave the pageNameWhitelist empty, if you use the default whitelist. I hope that is still correct. 😉

**Comment by ryancramerdesign** [comment]
@AndZyk It looks like you may be overwriting the default pageNameWhitelist with that line? If you want it to use the default, I would remove or comment out that pageNameWhitelist line, so that PW's default remains in place. While the default whitelist likely has the characters you are wanting, just in case it doesn't, let me know what those characters are and I will test here.

**Comment by ghost** [comment]
@ryancramerdesign 

Thank you for the hint. I was indeed overwriting the default pageNameWhitelist. I have misread your blog post, when you explained this feature and thought I have to leave the pageNameWhitelist blank to use the default one. Interestingly it has worked for me this way and I had used it this way on many sites.

Now I have removed this line from my config file and I can add and edit pages with Umlauts again. I think you can finally close this issue. 😉

**Comment by ryancramerdesign** [comment]
@AndZyk Great, sounds good thanks for testing that out. I'm not sure why it would have been working before if pageNameWhitelist was blank, but if blank I believe it would revert to default pageName format which is ascii [-_.a-zA-Z0-9]. I will keep an eye out for similar reports just in case. Thanks.
