### ISSUE TITLE
Multiple image upload in edge not working properly

### ISSUE THREAD

**Issue by philschenker** [processwire/processwire-issues#816]
### Short description of the issue

Uploading multiple images in Microsoft Edge not possible.

### Expected behavior

I try to upload multiple pictures (56) under Microsoft Edge. I expect that all pictures appear in the respective field after pressing "open" in file-manager.

### Actual behavior

My Ram goes up to 5GB and then it seems Edge is like reloading the page and nothing was uploaded. In Firefox I have no problem. To add is that I've tried it under Edge with 10 pictures, that is working correctly.

### Optional: Screenshots/Links that demonstrate the issue

None

### Optional: Suggestion for a possible fix

None

### Steps to reproduce the issue

1. Use Microsoft Edge
2. Upload 60 pictures with ~4.5MB / 20Mpixels into an images field that has max 1200x1200px setting

### Setup/Environment

<strong>Server Details</strong>

|Software|Version|
|------:|:-------|
|ProcessWire|3.0.123|
|PHP|7.1.26|
|Webserver|Apache|
|MySQL|10.1.37-MariaDB|
<details><summary><strong>Server Settings</strong></summary>

|Parameter|Value|
|------:|:-------|
|allow_url_fopen|1|
|max_execution_time|240 (changeable)|
|max_input_nesting_level|64|
|max_input_time|60|
|max_input_vars|20000|
|memory_limit|2048M|
|post_max_size|256M|
|upload_max_filesize|256M|
|xdebug||
|xdebug.max_nesting_level||
|mod_rewrite|1|
|mod_security||
|GD|bundled (2.1.0 compatible)|
|GIF|1|
|JPG|1|
|PNG|1|
|EXIF Support|1|
|FreeType|1|
|Imagick Extension|1|
</details><details><summary><strong>Module Details</strong></summary>

|Module ClassName|Version|
|------:|:-------|
|CroppableImage3|1.1.16|
|EmailObfuscation|1.1.1|
|FieldtypeCroppableImage3|1.1.16|
|InputfieldCroppableImage3|1.1.16|
|MarkupSitemapXML|1.1.0|
|ProcessCroppableImage3|1.1.16|
|ProcessPageDelete|1.2.4|
|ProcessWireUpgrade|0.0.7|
|ProcessWireUpgradeCheck|0.0.7|
|SimpleContactForm|1.0.7|
|TextformatterVideoEmbed|1.1.1|
|TracyDebugger|4.17.7|
</details>

**Comment by netcarver** [comment]
@philschenker Can you post the exact version of Edge that you are having issues with? 

Can anyone else reproduce this issue?

**Comment by matjazpotocnik** [comment]
I can't help here as I don't have Edge, but maybe it would help to bump post_max_size and upload_max_filesize? On the other hand, Edge is getting a new engine, maybe we should wait until that happens and test it then?

**Comment by philschenker** [comment]
@netcarver I used 42.17134.1.0 (Microsoft EdgeHTML 17.17134) to test this. It is to mention that I tried it because someone else had the exact same issue.

@matjazpotocnik No for sure this will not do anything, as it is working properly in Firefox/Chrome

**Comment by netcarver** [comment]
@philschenker Thank you.

Might be worth noting a similar problems were reported [here](https://github.com/ckfinder/ckfinder/issues/358) and [here](https://github.com/axios/axios/issues/1417#issuecomment-387683178) regarding the same version of Edge, though they don't seem to be exact copies of your issue.

There's another _very similar_ report [here](https://github.com/mitodl/open-discussions/issues/1140) but I can't turn up a version number. That issue was fixed on their project by [this PR](https://github.com/mitodl/open-discussions/pull/1155) - but it's python. Still, it might provide a clue.

Other people are reporting generic file upload issues. Here's [a conversation](https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/windows-10-edge-cannot-upload-files-onto-websites/b5ce5ca4-214b-448c-83d1-0c8e72501358) that contains a suggested fix part way down the first page, from a user called "metaz" (sorry, can't link directly as that Microsoft forum doesn't seem to be using IDs on the posts!) Worth noting that 142 users reported having the same problem.

![screeny-0067](https://user-images.githubusercontent.com/16049/53986253-869c0000-4115-11e9-8ece-e476d7587356.png)

The fix from metaz seems to work for some people.

Keep finding more as I scroll down my google search results. Here's [another](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10759529/) and a [form submission problem](https://stackoverflow.com/questions/53777315/symfony-3-form-action-undefined-route-microsoft-edge) vs your version.

Not sure exactly where that leaves us though.

**Comment by netcarver** [comment]
Of course, still doesn't explain why uploading 10 images works. I can only think that you are hitting a limit within Edge itself.

**Comment by netcarver** [comment]
@philschenker Did you check to see if Metaz's solution solved the mystery for you?

> Edge seems to require exclusive access to files when uploading them. Excel and Word only allow read access to opened documents, causing Edge to not accept the file for upload. Simply closing your document before uploading should fix you problem.

Perhaps one of the large group of files you were attempting to upload had some kind of lock open on it?

**Comment by philschenker** [comment]
Hi @netcarver, thanks for pointing me to Metaz's solution didn't find it in the first run and forgot about this issue on my holidays.

I tried it again, freshly booted Win10, opened Edge and tried to upload all the pictures (I paid attention to not open the pictures in any other program). Unfortunately, nothing is happening. still the same behavior.

**Comment by Toutouwai** [comment]
@philschenker, when you say that you are seeing this problem with Edge does this mean that you don't get the problem when you upload the same images with a different browser? What other browsers have you tested?

Do you have client-side resizing enabled for the images field?

![2019-04-30_122249](https://user-images.githubusercontent.com/1538852/56935022-bb8b6880-6b42-11e9-85a5-119189015a8a.png)

Maybe you are running out of memory or exceeding the max execution time if you are trying to resize such a large number of images server-side.

**Comment by Toutouwai** [comment]
Also, I see you have the non-core FieldtypeCroppableImage module installed. Can you please confirm that the upload issue is occurring in a core Images field and not a non-core field? If it's not a core issue then you should raise the issue in the module's support thread in the forums.

**Comment by philschenker** [comment]
Hi @Toutouwai Thanks for getting back! I tested Chrome and Firefox, which I usually take for uploading pictures (both are working like a charm!). That Edge is not working was detected by a friend who had this issue, then I reproduced it on my machine with the same processwire installation.

Answers to your questions:
- It is a core-image field
- Client-side resize is enabled
--> I quickly disabled it and it works in edge with server-side setting. So this issue is then probably in the Client-side scripts. Maybe some sort of a memory leak in js that only appears in edge?

**Comment by Toutouwai** [comment]
> So this issue is then probably in the Client-side scripts.

Yes, it sounds like that's the case. The PW client-side resizing is based on [HTML5 Image Uploader](https://github.com/rossturner/HTML5-ImageUploader), and there's an open issue that's probably relevant: https://github.com/rossturner/HTML5-ImageUploader/issues/8
Unfortunately the issue has been open for over two years already and it sounds like the library author isn't confident about fixing it.

**Comment by philschenker** [comment]
Yeah that really sounds like this is the case. Thanks for helping with debugging to all of you! But unfortunately, this sounds like the issue could even lie in Edge itself...

**Comment by netcarver** [comment]
@Toutouwai Robin - thanks so much for your help on this one, great detective work!

@philschenker Philippe, do you think this issue can now be closed here?

**Comment by philschenker** [comment]
Hi thanks for staying on it. I didn't had the issue again and as it turned out its edges problem not processwire's so yes you can close it.

Thanks for your work guys!

**Comment by netcarver** [comment]
Done, thanks!
